import React from 'react'
import Head from 'next/head'

type Props = {
  title: string;
}

const HtmlHead: React.FC<Props> = (props: Props) => {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://unpkg.com/modern-css-reset/dist/reset.min.css" />

        {/* <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/pure-min.css" integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5" crossOrigin="anonymous" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default HtmlHead